# Generated by Django 4.1.3 on 2022-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_employee_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee', models.ManyToManyField(to='office.employee')),
                ('office', models.ManyToManyField(to='office.company')),
            ],
        ),
    ]
