# Generated by Django 4.1.3 on 2022-11-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_officeresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeresource',
            name='issuedate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='officeresource',
            name='reasontobuy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
